version: 2.1
jobs:
  test:
    docker:
      - image: buildkite/puppeteer:v3.0.4
    steps:
      - run: sh scripts/install-git-lfs.sh
      - checkout
      - run: yarn --frozen-lockfile
      - run: yarn flow
      - run: yarn lint
      - run: yarn test --maxWorkers=2
      - run:
          command: yarn cosmos
          background: true
      - run: yarn test:visual --maxWorkers=2
      - store_artifacts:
          path: web/__image_snapshots__/__diff_output__
workflows:
  flatris:
    jobs:
      - test
